[package]
name = "aurora-engine-tests-connector"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
description = "ETH connector tests"
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
autobenches = false

[dev-dependencies]
anyhow.workspace = true
aurora-engine-types = { workspace = true, features = ["std", "impl-serde"] }
cargo-near-build = { workspace = true, features = ["build_internal"] }
near-sdk = { workspace = true, features = ["non-contract-usage"] }
near-workspaces.workspace = true
reqwest.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros"] }
zip = { workspace = true }

[lints]
workspace = true

[features]
